name: CI

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Run tests
      run: dotnet test -c Release --no-build

  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Run
      run: dotnet run -c Release --no-build -- all
      working-directory: ./src/AoC_2022

  benchmark:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Run All_Days_Benchmark
      run: dotnet run -c Release --no-build --filter AoC_2022.Benchmarks.All_Days_Benchmark.SolveAll
      working-directory: ./src/AoC_2022.Benchmarks

    - name: 'Upload ${{ matrix.os }} artifacts'
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-${{ matrix.os }}-${{ github.run_number }}
        path: ./src/AoC_2022.Benchmarks/BenchmarkDotNet.Artifacts/results/
        if-no-files-found: error
